import { useCallback, useMemo } from 'react';

const dictionaries = {
  uz: {
    languageName: 'O‘zbekcha', home: 'Bosh sahifa', catalog: 'Katalog', studio: 'Studiya', orders: 'Buyurtmalar', profile: 'Profil', settings: 'Sozlamalar',
    greeting: 'O‘zingizga mos forma yarating', greetingSub: 'Jamoangiz uchun o‘ziga xos dizayn.', startDesign: 'Dizaynni boshlash', popular: 'Mashhur modellar', all: 'Barchasi', collection: '2024 KOLLEKSIYASI', search: 'Modelni qidirish', football: 'Futbol', street: 'Street', kids: 'Bolalar',
    customize: 'Moslashtirish', baseKit: 'ASOSIY KOMPLEKT', description: 'Yengil va qulay forma. Ism, raqam va ranglarni studiyada o‘zingiz tanlang.', fabric: 'poliester', designTime: 'dizayn vaqti', sizes: 'o‘lchamlar',
    designStudio: 'Dizayn studiyasi', studioSub: 'Formangizni o‘zingiz yarating', preview: 'OLD TOMON KO‘RINISHI', colors: 'FORMA RANGI', nameNumber: 'ISM VA RAQAM', namePlaceholder: 'Formadagi ism', addToCart: 'Savatga qo‘shish', openCart: 'Savatni ochish', cart: 'Savat', emptyCart: 'Savat bo‘sh', emptyCartSub: 'Birinchi komplektingizni dizayn studiyasida yarating.', goStudio: 'Studiyaga o‘tish', items: 'ta komplekt', products: 'Mahsulotlar', delivery: 'Yetkazib berish', free: 'Bepul', total: 'Jami', checkout: 'Buyurtma berish', mockCheckout: 'Demo rejim: backend ulanganidan keyin haqiqiy to‘lov shu yerda ishlaydi.',
    myOrders: 'Buyurtmalarim', ordersSub: 'Har bir buyurtmani kuzating', activeOrder: 'FAOL BUYURTMA', production: 'Ishlab chiqarilmoqda', delivered: 'Yetkazib berildi', history: 'TARIX', allOrders: 'Barcha buyurtmalar',
    myProfile: 'Profilim', profileSub: 'Ma’lumotlar va sozlamalar', account: 'AKKAUNT', personalData: 'Shaxsiy ma’lumotlar', addresses: 'Yetkazib berish manzillari', favorites: 'Sevimlilar', help: 'Yordam va qo‘llab-quvvatlash', settingsLabel: 'Sozlamalar', language: 'Ilova tili', languageSub: 'O‘zbekcha, ruscha yoki inglizcha', save: 'Saqlash', back: 'Orqaga', arTitle: 'AR orqali kiyib ko‘rish', arSub: 'Keyingi bosqichda kamera ulanadi', favoriteAdded: 'Sevimlilarga qo‘shildi', favoriteRemoved: 'Sevimlilardan olib tashlandi', added: 'Mahsulot savatga qo‘shildi', ok: 'Tushunarli',
  },
  ru: {
    languageName: 'Русский', home: 'Главная', catalog: 'Каталог', studio: 'Студия', orders: 'Заказы', profile: 'Профиль', settings: 'Настройки', greeting: 'Создайте свою форму', greetingSub: 'Уникальный дизайн для вашей команды.', startDesign: 'Начать дизайн', popular: 'Популярные модели', all: 'Все', collection: 'КОЛЛЕКЦИЯ 2024', search: 'Найти модель', football: 'Футбол', street: 'Street', kids: 'Детские', customize: 'Настроить', baseKit: 'БАЗОВЫЙ КОМПЛЕКТ', description: 'Лёгкая и удобная форма. Выберите имя, номер и цвета в студии.', fabric: 'полиэстер', designTime: 'время дизайна', sizes: 'размеры', designStudio: 'Дизайн-студия', studioSub: 'Создайте форму сами', preview: 'ВИД СПЕРЕДИ', colors: 'ЦВЕТ ФОРМЫ', nameNumber: 'ИМЯ И НОМЕР', namePlaceholder: 'Имя на форме', addToCart: 'В корзину', openCart: 'Открыть корзину', cart: 'Корзина', emptyCart: 'Корзина пуста', emptyCartSub: 'Создайте первый комплект в дизайн-студии.', goStudio: 'Перейти в студию', items: 'комплектов', products: 'Товары', delivery: 'Доставка', free: 'Бесплатно', total: 'Итого', checkout: 'Оформить заказ', mockCheckout: 'Demo-режим: реальная оплата появится после подключения backend.', myOrders: 'Мои заказы', ordersSub: 'Следите за каждым заказом', activeOrder: 'АКТИВНЫЙ ЗАКАЗ', production: 'В производстве', delivered: 'Доставлен', history: 'ИСТОРИЯ', allOrders: 'Все заказы', myProfile: 'Мой профиль', profileSub: 'Данные и настройки', account: 'АККАУНТ', personalData: 'Личные данные', addresses: 'Адреса доставки', favorites: 'Избранное', help: 'Помощь и поддержка', settings: 'Настройки', settingsLabel: 'Настройки', language: 'Язык приложения', languageSub: 'Узбекский, русский или английский', save: 'Сохранить', back: 'Назад', arTitle: 'Примерить в AR', arSub: 'Камера подключится на следующем этапе', favoriteAdded: 'Добавлено в избранное', favoriteRemoved: 'Убрано из избранного', added: 'Товар добавлен в корзину', ok: 'Понятно', languageName: 'Русский',
  },
  en: {
    languageName: 'English', home: 'Home', catalog: 'Catalog', studio: 'Studio', orders: 'Orders', profile: 'Profile', settings: 'Settings', greeting: 'Create your own kit', greetingSub: 'A unique design for your team.', startDesign: 'Start designing', popular: 'Popular models', all: 'All', collection: '2024 COLLECTION', search: 'Search model', football: 'Football', street: 'Street', kids: 'Kids', customize: 'Customize', baseKit: 'BASE KIT', description: 'A light and comfortable kit. Choose name, number and colors in the studio.', fabric: 'polyester', designTime: 'design time', sizes: 'sizes', designStudio: 'Design studio', studioSub: 'Build your own kit', preview: 'FRONT VIEW', colors: 'KIT COLOR', nameNumber: 'NAME AND NUMBER', namePlaceholder: 'Name on kit', addToCart: 'Add to cart', openCart: 'Open cart', cart: 'Cart', emptyCart: 'Your cart is empty', emptyCartSub: 'Create your first kit in the design studio.', goStudio: 'Go to studio', items: 'kits', products: 'Products', delivery: 'Delivery', free: 'Free', total: 'Total', checkout: 'Checkout', mockCheckout: 'Demo mode: real payment will work after backend integration.', myOrders: 'My orders', ordersSub: 'Track every order', activeOrder: 'ACTIVE ORDER', production: 'In production', delivered: 'Delivered', history: 'HISTORY', allOrders: 'All orders', myProfile: 'My profile', profileSub: 'Your data and settings', account: 'ACCOUNT', personalData: 'Personal data', addresses: 'Delivery addresses', favorites: 'Favorites', help: 'Help and support', settingsLabel: 'Settings', language: 'App language', languageSub: 'Uzbek, Russian or English', save: 'Save', back: 'Back', arTitle: 'Try on with AR', arSub: 'Camera will be connected later', favoriteAdded: 'Added to favorites', favoriteRemoved: 'Removed from favorites', added: 'Product added to cart', ok: 'Got it', languageName: 'English',
  },
};

export function useTranslation(language) {
  const dictionary = dictionaries[language] || dictionaries.uz;
  const t = useCallback((key) => dictionary[key] || dictionaries.uz[key] || key, [dictionary]);
  return useMemo(() => ({ t, languageName: dictionary.languageName }), [t, dictionary.languageName]);
}

export const languageOptions = Object.keys(dictionaries).map((code) => ({ code, label: dictionaries[code].languageName }));
