import React from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, radii, spacing } from '../constants/theme';
import { Button, Card, Header, Screen, formatMoney } from '../components/ui/Common';
import { JerseyPreview } from '../components/ui/JerseyPreview';

export default function CartScreen({ cart, removeFromCart, clearCart, t, onBack }) {
  const total = cart.reduce((sum, item) => sum + item.price, 0);
  const checkout = () => Alert.alert(t('checkout'), t('mockCheckout'));
  return <Screen><Header title={t('cart')} subtitle={`${cart.length} ${t('items')}`} onBack={onBack} />{cart.length === 0 ? <Card style={styles.empty}><Text style={styles.emptyIcon}>＋</Text><Text style={styles.emptyTitle}>{t('emptyCart')}</Text><Text style={styles.emptyText}>{t('emptyCartSub')}</Text><Button onPress={onBack} style={styles.emptyButton}>{t('goStudio')} →</Button></Card> : <><View style={styles.list}>{cart.map((item, index) => <View key={`${item.id}-${index}`} style={styles.item}><View style={[styles.thumb, { backgroundColor: item.color }]}><JerseyPreview product={item} number={item.customNumber} compact /></View><View style={{ flex: 1 }}><Text style={styles.name}>{item.name}</Text><Text style={styles.sub}>{item.customName} · №{item.customNumber}</Text><Text style={styles.price}>{formatMoney(item.price)}</Text></View><Pressable onPress={() => removeFromCart(index)}><Text style={styles.remove}>×</Text></Pressable></View>)}</View><Card style={styles.summary}><Row label={t('products')} value={formatMoney(total)} /><Row label={t('delivery')} value={t('free')} /><View style={styles.divider} /><Row label={t('total')} value={formatMoney(total)} strong /></Card><Button onPress={checkout}>{t('checkout')} →</Button><Pressable onPress={clearCart} style={styles.clear}><Text style={styles.clearText}>Savatni tozalash</Text></Pressable></>}</Screen>;
}
function Row({ label, value, strong }) { return <View style={styles.row}><Text style={[styles.rowLabel, strong && styles.strong]}>{label}</Text><Text style={[styles.rowValue, strong && styles.strong]}>{value}</Text></View>; }
const styles = StyleSheet.create({ empty: { alignItems: 'center', marginTop: spacing.xxxl }, emptyIcon: { color: colors.accent, fontSize: 42 }, emptyTitle: { color: colors.text, fontSize: 20, fontWeight: '900', marginTop: spacing.md }, emptyText: { color: colors.muted, textAlign: 'center', lineHeight: 20, marginTop: spacing.sm }, emptyButton: { marginTop: spacing.xl }, list: { gap: spacing.md, marginBottom: spacing.xl }, item: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: colors.surface, padding: spacing.md, borderRadius: radii.lg }, thumb: { width: 60, height: 70, borderRadius: radii.md, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, name: { color: colors.text, fontWeight: '900', fontSize: 13 }, sub: { color: colors.muted, fontSize: 11, marginTop: 4 }, price: { color: colors.text, fontWeight: '800', fontSize: 12, marginTop: 7 }, remove: { color: colors.muted, fontSize: 26, padding: 5 }, summary: { gap: spacing.md, marginBottom: spacing.lg }, row: { flexDirection: 'row', justifyContent: 'space-between' }, rowLabel: { color: colors.muted, fontSize: 12 }, rowValue: { color: colors.text, fontSize: 12, fontWeight: '700' }, strong: { color: colors.text, fontSize: 16, fontWeight: '900' }, divider: { borderTopWidth: 1, borderTopColor: colors.border }, clear: { alignItems: 'center', padding: spacing.lg }, clearText: { color: colors.muted, fontSize: 12 } });
