import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { colors, radii, spacing } from '../constants/theme';
import { orders } from '../data/mockData';
import { Card, Header, Screen, SectionTitle, formatMoney } from '../components/ui/Common';
import { JerseyPreview } from '../components/ui/JerseyPreview';

export default function OrdersScreen({ t }) {
  return <Screen><Header title={t('myOrders')} subtitle={t('ordersSub')} /><Card style={styles.tracker}><View style={styles.row}><Text style={styles.overline}>{t('activeOrder')}</Text><Text style={styles.id}>{orders[0].id}</Text></View><Text style={styles.trackerTitle}>{t('production')}</Text><Text style={styles.trackerSub}>29.08.2024 · 3-bosqich</Text><View style={styles.progress}><View style={styles.done} /></View><View style={styles.labels}><Text>Dizayn</Text><Text>Ishlab chiqarish</Text><Text>Yetkazish</Text></View></Card><SectionTitle eyebrow={t('history')} title={t('allOrders')} /><View style={styles.list}>{orders.map((order, index) => <Card key={order.id} style={styles.order}><View style={styles.thumb}><JerseyPreview product={{ color: index ? '#F29C59' : '#5A66DE', accent: '#BFD5FF' }} compact /></View><View style={{ flex: 1 }}><View style={styles.row}><Text style={styles.id}>{order.id}</Text><Text style={order.status === 'production' ? styles.orange : styles.green}>{order.status === 'production' ? t('production') : t('delivered')}</Text></View><Text style={styles.product}>{order.product} · {order.size}</Text><Text style={styles.date}>{order.date} · {formatMoney(order.total)}</Text></View></Card>)}</View></Screen>;
}
const styles = StyleSheet.create({ tracker: { backgroundColor: '#20275E', marginBottom: spacing.xxxl }, row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, overline: { color: colors.success, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, id: { color: colors.text, fontSize: 12, fontWeight: '800' }, trackerTitle: { color: colors.text, fontSize: 19, fontWeight: '900', marginTop: spacing.lg }, trackerSub: { color: colors.muted, fontSize: 12, marginTop: 5 }, progress: { height: 5, borderRadius: 3, backgroundColor: colors.border, marginTop: spacing.xl, overflow: 'hidden' }, done: { height: 5, width: '58%', backgroundColor: colors.accent }, labels: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.sm }, labelText: { color: colors.muted, fontSize: 10 }, list: { gap: spacing.md }, order: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, thumb: { width: 58, height: 68, borderRadius: radii.md, backgroundColor: colors.surfaceRaised, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, orange: { color: colors.accent, fontSize: 10, fontWeight: '800' }, green: { color: colors.success, fontSize: 10, fontWeight: '800' }, product: { color: colors.text, fontSize: 12, fontWeight: '800', marginTop: spacing.sm }, date: { color: colors.muted, fontSize: 10, marginTop: 4 } });
