import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { colors, radii, spacing } from '../constants/theme';
import { Button, Header, Screen, formatMoney } from '../components/ui/Common';
import { JerseyPreview } from '../components/ui/JerseyPreview';

export default function ProductScreen({ product, t, onBack, onCustomize }) {
  return <Screen><Header title={product.name} subtitle={t('baseKit')} onBack={onBack} /><View style={[styles.preview, { backgroundColor: product.color }]}><Text style={styles.badge}>{product.badge}</Text><JerseyPreview product={product} /></View><View style={styles.titleRow}><View><Text style={styles.overline}>{t('baseKit')}</Text><Text style={styles.title}>{product.name}</Text></View><Text style={styles.price}>{formatMoney(product.price)}</Text></View><Text style={styles.description}>{t('description')}</Text><View style={styles.specs}><View><Text style={styles.value}>100%</Text><Text style={styles.label}>{t('fabric')}</Text></View><View><Text style={styles.value}>48 h</Text><Text style={styles.label}>{t('designTime')}</Text></View><View><Text style={styles.value}>7–XXL</Text><Text style={styles.label}>{t('sizes')}</Text></View></View><Button onPress={() => onCustomize(product)}>{t('customize')} →</Button></Screen>;
}
const styles = StyleSheet.create({ preview: { height: 320, borderRadius: radii.xl, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', marginBottom: spacing.xl }, badge: { position: 'absolute', top: spacing.lg, left: spacing.lg, color: colors.black, fontWeight: '900', fontSize: 10 }, titleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, overline: { color: colors.info, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, title: { color: colors.text, fontSize: 24, fontWeight: '900', marginTop: 4 }, price: { color: colors.accent, fontWeight: '900', fontSize: 13 }, description: { color: colors.muted, fontSize: 13, lineHeight: 21, marginTop: spacing.md }, specs: { flexDirection: 'row', justifyContent: 'space-between', backgroundColor: colors.surface, borderRadius: radii.lg, padding: spacing.lg, marginVertical: spacing.xl }, value: { color: colors.text, fontSize: 17, fontWeight: '900' }, label: { color: colors.muted, fontSize: 10, marginTop: 4 } });
