import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { colors, radii, spacing } from '../constants/theme';
import { profile } from '../data/mockData';
import { Card, Header, Screen } from '../components/ui/Common';

export default function ProfileScreen({ t, onSettings }) {
  const rows = [[t('personalData'), 'O‘lcham, bo‘y va vazn', '♙'], [t('addresses'), 'Toshkent, 1 ta saqlangan', '⌖'], [t('favorites'), '4 ta komplekt', '♡'], [t('help'), '24/7 aloqa', '?']];
  return <Screen><Header title={t('myProfile')} subtitle={t('profileSub')} /><Card style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>A</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{profile.name}</Text><Text style={styles.phone}>{profile.phone}</Text></View></Card><Text style={styles.label}>{t('account')}</Text>{rows.map(([title, sub, icon]) => <View key={title} style={styles.row}><Text style={styles.icon}>{icon}</Text><View style={{ flex: 1 }}><Text style={styles.title}>{title}</Text><Text style={styles.sub}>{sub}</Text></View></View>)}<Pressable onPress={onSettings} style={styles.row}><Text style={styles.icon}>⚙</Text><View style={{ flex: 1 }}><Text style={styles.title}>{t('settings')}</Text><Text style={styles.sub}>{t('languageSub')}</Text></View><Text style={styles.arrow}>›</Text></Pressable><Text style={styles.version}>FORMO v0.2.0 · Mock API</Text></Screen>;
}
const styles = StyleSheet.create({ profile: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.xl }, avatar: { width: 54, height: 54, borderRadius: radii.md, backgroundColor: colors.accent, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.black, fontWeight: '900', fontSize: 24 }, name: { color: colors.text, fontSize: 16, fontWeight: '900' }, phone: { color: colors.muted, fontSize: 12, marginTop: 4 }, label: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1, marginBottom: spacing.sm }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, paddingVertical: spacing.lg, borderBottomWidth: 1, borderBottomColor: colors.border }, icon: { color: colors.primary, fontSize: 21, width: 25, textAlign: 'center' }, title: { color: colors.text, fontSize: 13, fontWeight: '800' }, sub: { color: colors.muted, fontSize: 11, marginTop: 4 }, arrow: { color: colors.accent, fontSize: 25 }, version: { color: '#59618D', textAlign: 'center', fontSize: 10, marginTop: spacing.xxxl } });
