import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radii, spacing } from '../constants/theme';
import { colorOptions, products } from '../data/mockData';
import { Button, Card, FieldLabel, Header, Screen, formatMoney } from '../components/ui/Common';
import { JerseyPreview } from '../components/ui/JerseyPreview';

export default function StudioScreen({ t, addToCart, cartCount, onOpenCart }) {
  const [color, setColor] = useState(colorOptions[0]);
  const [name, setName] = useState('OYIM');
  const [number, setNumber] = useState('10');
  const product = { ...products[0], color, accent: color === '#F5A55E' ? '#201944' : '#BFD5FF' };
  const item = { ...product, customName: name.trim() || 'OYIM', customNumber: number || '10' };
  return <Screen><Header title={t('designStudio')} subtitle={t('studioSub')} /><View style={styles.preview}><Text style={styles.previewLabel}>{t('preview')}</Text><JerseyPreview product={product} number={number || '10'} /><Text style={[styles.backName, { color: product.accent }]}>{name || 'ISM'}</Text></View><FieldLabel>{t('colors')}</FieldLabel><View style={styles.colors}>{colorOptions.map((option) => <Pressable key={option} onPress={() => setColor(option)} style={[styles.dot, { backgroundColor: option }, color === option && styles.selected]} />)}</View><FieldLabel>{t('nameNumber')}</FieldLabel><View style={styles.inputs}><TextInput value={name} onChangeText={setName} placeholder={t('namePlaceholder')} placeholderTextColor={colors.muted} style={[styles.textInput, { flex: 1 }]} maxLength={10} /><TextInput value={number} onChangeText={setNumber} placeholder="10" placeholderTextColor={colors.muted} style={[styles.textInput, styles.number]} keyboardType="number-pad" maxLength={2} /></View><Card style={styles.footer}><View><Text style={styles.totalLabel}>{t('total')}</Text><Text style={styles.total}>{formatMoney(item.price)}</Text></View><Button onPress={() => { addToCart(item); Alert.alert(t('added'), t('ok')); }} style={styles.add}>{t('addToCart')} +</Button></Card>{cartCount > 0 ? <Pressable onPress={onOpenCart} style={styles.cartLink}><Text style={styles.cartLinkText}>{t('openCart')} · {cartCount} {t('items')} →</Text></Pressable> : null}<Card style={styles.ar}><Text style={styles.arIcon}>⌾</Text><View style={{ flex: 1 }}><Text style={styles.arTitle}>{t('arTitle')}</Text><Text style={styles.arText}>{t('arSub')}</Text></View></Card></Screen>;
}
const styles = StyleSheet.create({ preview: { height: 350, borderRadius: radii.xl, backgroundColor: '#151D49', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, previewLabel: { position: 'absolute', top: spacing.lg, left: spacing.lg, color: colors.success, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, backName: { position: 'absolute', bottom: 28, fontSize: 20, fontWeight: '900', letterSpacing: 2 }, colors: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.md }, dot: { width: 38, height: 38, borderRadius: 19, borderWidth: 3, borderColor: 'transparent' }, selected: { borderColor: colors.white, transform: [{ scale: 1.1 }] }, inputs: { flexDirection: 'row', gap: spacing.sm }, textInput: { height: 50, borderRadius: radii.md, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: spacing.md, fontSize: 14, fontWeight: '700' }, number: { width: 72, textAlign: 'center' }, footer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.xl }, totalLabel: { color: colors.muted, fontSize: 10, fontWeight: '900' }, total: { color: colors.text, fontSize: 17, fontWeight: '900', marginTop: 4 }, add: { paddingHorizontal: spacing.md }, cartLink: { alignItems: 'center', paddingVertical: spacing.lg }, cartLinkText: { color: colors.accent, fontSize: 12, fontWeight: '800' }, ar: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, arIcon: { color: colors.primary, fontSize: 28 }, arTitle: { color: colors.text, fontWeight: '900', fontSize: 13 }, arText: { color: colors.muted, fontSize: 11, marginTop: 3 } });
