export const STATUS_LABELS = {
  yangi: 'YANGI',
  bosmada: 'BOSMADA',
  tayyor: 'TAYYOR',
};

export const STATUS_VARIANTS = {
  yangi: 'teal',
  bosmada: 'indigo',
  tayyor: 'amber',
};

export const WORKFLOW_STEPS = [
  { id: 'qabul', label: 'Qabul qilindi', done: true },
  { id: 'tayyorlandi', label: 'Tayyorlandi', done: true },
  { id: 'bosish', label: 'Bosish', active: true },
  { id: 'tayyor', label: 'Tayyor', done: false },
];

export const queueOrders = [
  {
    id: 'F-24822',
    customer: 'DILSHOD',
    initials: 'D',
    summaryText: 'Futbolka · 7 · qizil XL · 1 dona',
    model: 'Formo Pro 24',
    number: 7,
    size: 'XL',
    fabric: 'Interlok',
    composition: '95% paxta · 5% elastan',
    qty: 1,
    printColor: 'Oq',
    jerseyColor: '#D72E3F',
    jerseyColorName: 'Qizil',
    location: 'Old · markaz',
    status: 'yangi',
    stage: 2,
    time: 'Bugun, 14:30',
    deadlineText: 'Bugun, 14:30 · 2 soat 18 daqiqa',
  },
  {
    id: 'F-24825',
    customer: 'LOLA',
    initials: 'L',
    summaryText: 'Futbolka · 11 · oq M · 2 dona',
    model: 'Formo Pro 24',
    number: 11,
    size: 'M',
    fabric: 'Interlok',
    composition: '95% paxta · 5% elastan',
    qty: 2,
    printColor: 'Qora',
    jerseyColor: '#ffffff',
    jerseyColorName: 'Oq',
    location: 'Old · markaz',
    status: 'bosmada',
    stage: 2,
    time: 'Bugun, 15:10',
    deadlineText: 'Bugun, 15:10 · 3 soat 00 daqiqa',
  },
  {
    id: 'F-24828',
    customer: 'SARDOR',
    initials: 'S',
    summaryText: 'Oversize · 23 · qora L · 1 dona',
    model: 'Oversize Street',
    number: 23,
    size: 'L',
    fabric: 'Futra',
    composition: '100% paxta',
    qty: 1,
    printColor: 'Oq',
    jerseyColor: '#111827',
    jerseyColorName: 'Qora',
    location: 'Orqa · markaz',
    status: 'yangi',
    stage: 0,
    time: 'Bugun, 16:00',
    deadlineText: 'Bugun, 16:00 · 3 soat 50 daqiqa',
  },
  {
    id: 'F-24831',
    customer: 'MADINA',
    initials: 'M',
    summaryText: 'Futbolka · 9 · ko\'k S · 3 dona',
    model: 'Formo Pro 24',
    number: 9,
    size: 'S',
    fabric: 'Interlok',
    composition: '95% paxta · 5% elastan',
    qty: 3,
    printColor: 'Oq',
    jerseyColor: '#2563eb',
    jerseyColorName: "Ko'k",
    location: 'Old · markaz',
    status: 'tayyor',
    stage: 3,
    time: 'Bugun, 16:45',
    deadlineText: 'Bugun, 16:45 · Tayyor bo\'ldi',
  },
];

export const STOCK_COLORS = [
  { name: 'Oq', hex: '#ffffff' },
  { name: 'Qora', hex: '#111827' },
  { name: 'Qizil', hex: '#D72E3F' },
  { name: "Ko'k", hex: '#2563eb' },
];

export const STOCK_SIZES = ['S', 'M', 'L', 'XL', 'XXL'];

export const stockMatrix = {
  Oq: { S: 12, M: 18, L: 24, XL: 9, XXL: 3 },
  Qora: { S: 8, M: 16, L: 21, XL: 7, XXL: 0 },
  Qizil: { S: 4, M: 6, L: 3, XL: 2, XXL: 0 },
  "Ko'k": { S: 10, M: 12, L: 8, XL: 5, XXL: 1 },
};

export const defectReasons = [
  { id: 'bosma-siljidi', label: 'Bosma siljidi', icon: 'move' },
  { id: 'mato-nuqsoni', label: 'Mato nuqsoni', icon: 'eye' },
  { id: 'notogri-olcham', label: "Noto'g'ri o'lcham", icon: 'ruler' },
];

export const batches = [
  { id: 'P-1042', model: 'Formo Pro 24', qty: 250, done: 170, status: 'bosmada', deadline: '10.10.2026' },
  { id: 'P-1043', model: 'Oversize Street', qty: 180, done: 180, status: 'tayyor', deadline: '08.10.2026' },
  { id: 'P-1044', model: 'Formo Pro 24', qty: 120, done: 18, status: 'yangi', deadline: '14.10.2026' },
];

export const employees = [
  {
    id: 1,
    name: 'Aziz Karimov',
    initials: 'AK',
    role: 'Smena boshlig\'i',
    factory: 'Chilonzor',
    phone: '+998 90 123 45 67',
    shiftStart: '09:00',
    shiftEnd: '18:00',
    language: "O'zbekcha",
    active: true,
    notifications: { push: true, sms: true, email: true },
  },
  {
    id: 2,
    name: 'Dilshod Nurmatov',
    initials: 'DN',
    role: 'Bosma operatori',
    factory: 'Chilonzor',
    phone: '+998 90 417 22 18',
    shiftStart: '09:00',
    shiftEnd: '18:00',
    language: "O'zbekcha",
    active: true,
    notifications: { push: true, sms: false, email: false },
  },
  {
    id: 3,
    name: 'Malika Saidova',
    initials: 'MS',
    role: 'Dizayner',
    factory: 'Chilonzor',
    phone: '+998 93 618 04 28',
    shiftStart: '09:00',
    shiftEnd: '18:00',
    language: "O'zbekcha",
    active: true,
    notifications: { push: true, sms: true, email: true },
  },
  {
    id: 4,
    name: 'Sardor Olimov',
    initials: 'SO',
    role: 'Bosma operatori',
    factory: 'Chilonzor',
    phone: '+998 99 440 13 09',
    shiftStart: '09:00',
    shiftEnd: '18:00',
    language: "O'zbekcha",
    active: true,
    notifications: { push: true, sms: false, email: false },
  },
  {
    id: 5,
    name: 'Nigora Zokirova',
    initials: 'NZ',
    role: 'Administrator',
    factory: 'Chilonzor',
    phone: '+998 97 155 88 41',
    shiftStart: '09:00',
    shiftEnd: '18:00',
    language: "O'zbekcha",
    active: true,
    notifications: { push: true, sms: true, email: true },
  },
];
